directories = ["cmd", "internal", "internal/app", "internal/server", "internal/loger"]
files = ["main.go", "file2.txt"]
comands = ["command1", "command2"]

[[contents]]
file = "file1.txt"
data = "hello"

[[contents]]
file = "file2.txt"
data = "fd"